sudo: false
language: python
python:
  - "3.6"
cache:
  directories:
    - $HOME/.pip-cache/
env:
  - TOX_ENV=py27-dj111
  - TOX_ENV=py36-dj111
  - TOX_ENV=py36-dj20
  - TOX_ENV=py36-dj21
install:
  - pip install --upgrade pip
  - pip install tox>=1.8.0
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
